development:
  adapter: sqlite3
  database: ":memory:"
  timeout: 500

test:
  adapter: sqlite3
  database: ":memory:"
  timeout: 500

production:
  adapter: sqlite3
  database: ":memory:"
  timeout: 500
